session/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
define('pagenation_count' ,5);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth' ]
], function () {
    
    Route::group([
        'middleware' => ['admin']
    ], function () {

    Route::group([
        'prefix' => 'clients',
        'as' => 'clients.'
    ], function () {
        Route::get('/get-clients', 'ClientController@getClients')->name('get-clients');
    });
    Route::resource('/clients', 'ClientController');



    Route::group([
        'prefix' => 'categories',
        'as' => 'categories.'
    ], function () {
        Route::get('/get-categories', 'CategoryController@getCategories')->name('get-categories');
    });
    Route::resource('/categories', 'CategoryController');



    Route::group([
        'prefix' => 'products',
        'as' => 'products.'
    ], function () {
        Route::get('/get-products', 'ProductController@getProducts')->name('get-products');
    });
    Route::resource('/products', 'ProductController');



    Route::group([
        'prefix' => 'orders',
        'as' => 'orders.'
    ], function () {
        Route::get('/get-orders', 'OrderController@getOrders')->name('get-orders');
    });
    
    Route::resource('/orders', 'OrderController');

    });


    Route::group([
        'prefix' => 'stocks',
        'as' => 'stocks.'
    ], function () {
        Route::get('/get-stocks', 'StockController@getStocks')->name('get-stocks');
    });
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::get('/search', 'SearchController@index')->name('search-for-product');
    Route::get('/search-product', 'SearchController@search');
    
    Route::resource('/stocks', 'StockController');

    Route::get('/create-inventory/{product}' , 'StockController@create')->name('inventory');
});


Route::group([
    'prefix' => 'orders',
    'as' => 'orders.'
], function () {
    Route::get('/get-orders', 'Front\BuyControlle@getOrders')->name('get-product-orders');
});

Route::get('/buy/{product}', 'Front\BuyController@create')->name('buyproduct');
Route::resource('/order', 'Front\BuyController');

Route::get('/', function () {
    return view('searchbox');
});


Auth::routes();
Route::get('/clients/register' , 'Auth\RegisterController@clientRegisterForm')->name('client-register-form');
Route::post('/clients/register' , 'Auth\RegisterController@registerclient')->name('register-client');
Route::get('/clients/login' , 'Auth\LoginController@clientLoginForm')->name('client-login-form');
Route::post('/clients/login' , 'Auth\LoginController@loginclient')->name('login-client');
Route::get('/clients/logout' , 'Auth\LoginController@clientlogout')->name('logout-client');

session/app/Order.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'date',
        'client_id',
        'user_id',
        'total_amount',
        'payment_methods_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function client()
    {
        return $this->belongsTo(Client::class, 'client_id');
    }

    public function products()
    {
        return $this->belongsToMany(
            Product::class,
            'details',
            'order_id',
            'product_id')
            ->withPivot(['price', 'quantity', 'total' , 'created_at'])
            ->withTimestamps();
    }
    public function payment()
    {
        return $this->belongsTo(paymentMethod::class, 'payment_methods_id');
    }
}

session/app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;
use App\Order;
use App\Client;
use App\User;
use App\Detail;
use App\Product;
use App\paymentMethod;
use App\Repository\Order\OrderRepositoryInterface;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    private $orderRepository;

    public function __construct(OrderRepositoryInterface $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('admin.order.index', [
            'orders' => $this->orderRepository->paginate($request)
            
        ]);
        
    }
    public function getOrders(Request $request)
    {
        return view('admin.order.table', [
            'orders' => Order::query()->paginate(pagenation_count)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.order.create', [
            'orders' => Order::all(),
            'clients'=> Client::all(),
            'users'=> User::all(),
            'products'=> Product::all(),
            'payments'=>paymentMethod::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = $this->orderRepository->create($request);
        return redirect(route('admin.orders.show',  $order));  
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order )
    {
        $order->load('products');
        return view('admin.order.show', [
            'order'=> $order
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('admin.order.edit', [
            'order' => $order,
            'orders' => Order::all(),
            'clients'=> Client::all(),
            'users'=> User::all(),
            'products'=> Product::all(),
            'payments'=>paymentMethod::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $request->merge([
            'user_id' => $request->user()->id
        ]);
        $order->update($request->all());
        $products=$request->get('products');
        $totalamount=0;
        foreach($products as $product){
            $quantity=$product['quantity'];
            $price=$product['price'];
            $total= $quantity * $price;
            $totalamount +=$total;
        }
        $order->total_amount =$totalamount;
        $order->save();
        $order->products()->sync($request->get('products'));
        $order->save();
        return redirect(route('admin.orders.show', $order));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();
        return  redirect(route('admin.orders.index'));
    }
}

session/resources/views/admin/order/create.blade.php
@extends('layouts.app')

@section('title', 'All Orders')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Orders</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.orders.index') }}">Orders</a></li>
                            <li class="breadcrumb-item active">Create new Orders</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.orders.store') }}" method="post">
                           @include('admin.order.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

session/resources/views/admin/order/edit.blade.php
@extends('layouts.app')

@section('title', 'All orders')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">orders</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.orders.index') }}">orders</a></li>
                            <li class="breadcrumb-item active">update order</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.orders.update', $order) }}"method="post">
                            @method('PUT')
                           @include('admin.order.formupdate')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

session/resources/views/admin/order/form.blade.php
@csrf
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label for="client_id">Client Name</label>
            <select name="client_id" id="client_id" class="form-control">
                <option>Not Set</option>
                @foreach($clients as $client)
                    <option value="{{ $client->id }}"
                        {{ old('client_id') == $client->id ? 'selected' : '' }}>
                        {{ $client->name }}
                    </option>
                @endforeach
            </select>
            @if ($errors->first('client_id'))
                <span class="text-danger">
          {{ $errors->first('client_id') }}
        </span>
            @endif

        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="payment_methods_id">Payment Method</label>
            <select name="payment_methods_id" id="payment_methods_id" class="form-control">
                @foreach($payments as $payment)
                    <option value="{{ $payment->id }}" selected > {{ $payment->name }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="date">Order Date</label>
            <input type="date" id="date" name="date" class="form-control" value="{{ old('date') }}">
            @if ($errors->first('date'))
                <span class="text-danger">
                  {{ $errors->first('date') }}
                </span>
            @endif

        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <h3>Products
            @if ($errors->first('products'))
                <span class="text-danger">
                  {{ $errors->first('products') }}
                </span>
            @endif

        </h3>

        <button type="button" class="btn btn-info" id="btn-add-new-product">Add Product</button>
    </div>
    <table class="table mt-3">
        <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody id="products-list">

        @if (old('products'))
            @foreach(old('products') as $rowId => $rowProduct)
                <tr id="product-{{$rowId}}">
                    <td>
                        <select name="products[{{$rowId}}][product_id]"
                                class="form-control input-product-product_id"
                                row-id="product-{{$rowId}}">
                            @foreach($products as $product)
                                @if ($product->id == $rowProduct['product_id'])
                                    <option value="{{ $product->id }}" selected data-price="{{ $product->price }}">
                                        {{ $product->name }} | {{ $product->price }}
                                    </option>
                                @else
                                    <option value="{{ $product->id }}" data-price="{{ $product->price }}">
                                        {{ $product->name }} | {{ $product->price }}
                                    </option>
                                @endif
                            @endforeach
                        </select>

                        @if ($errors->first('products.' . $rowId . '.product_id'))
                            <span class="text-danger">
                              {{ $errors->first('products.' . $rowId . '.product_id') }}
                            </span>
                        @endif
                    </td>
                    <td>
                        <input type="number"
                               name="products[{{$rowId}}][quantity]"
                               value="{{ $rowProduct['quantity']?? 1 }}"
                               row-id="product-{{$rowId}}"
                               class="form-control input-product-quantity">
                        @if ($errors->first('products.' . $rowId . '.quantity'))
                            <span class="text-danger">
                              {{ $errors->first('products.' . $rowId . '.quantity') }}
                            </span>
                        @endif
                    </td>
                    <td>
                        <input type="number"
                               name="products[{{$rowId}}][price]"
                               readonly
                               class="form-control input-product-price"
                               row-id="product-{{$rowId}}"
                               value="{{ $rowProduct['price']?? 1 }}">
                        @if ($errors->first('products.' . $rowId . '.price'))
                            <span class="text-danger">
                              {{ $errors->first('products.' . $rowId . '.price') }}
                            </span>
                        @endif
                    </td>
                    <td>
                        <input type="number"
                               name="products[{{$rowId}}][total]"
                               readonly
                               class="form-control input-product-total"
                               row-id="product-{{$rowId}}"
                               value="{{ $rowProduct['total'] == 0 ? $rowProduct['price'] : $rowProduct['total'] }}">

                        @if ($errors->first('products.' . $rowId . '.total'))
                            <span class="text-danger">
                              {{ $errors->first('products.' . $rowId . '.total') }}
                            </span>
                        @endif
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger row-delete" row-id="product-{{$rowId}}">-</button>
                    </td>
                </tr>
            @endforeach
        @else
            <tr id="product-1">
                <td>
                    <select name="products[1][product_id]"
                            class="form-control input-product-product_id"
                            row-id="product-1">
                        @foreach($products as $product)
                            <option value="{{ $product->id }}" data-price="{{ $product->price }}">
                                {{ $product->name }} | {{ $product->price }}
                            </option>
                        @endforeach
                    </select>
                </td>
                <td>
                    <input type="number"
                           name="products[1][quantity]"
                           value="1"
                           row-id="product-1"
                           class="form-control input-product-quantity">
                </td>
                <td>
                    <input type="number"
                           name="products[1][price]"
                           readonly
                           class="form-control input-product-price"
                           row-id="product-1"
                           value="{{ $products->first()->price }}">
                </td>
                <td>
                    <input type="number"
                           name="products[1][total]"
                           readonly
                           class="form-control input-product-total"
                           row-id="product-1"
                           value="{{ $products->first()->price }}">
                </td>
                <td>
                    <button type="button" class="btn btn-danger row-delete" row-id="product-1">-</button>
                </td>
            </tr>
        @endif

        </tbody>

    </table>
</div>
<div class="text-center">
    <button type="submit" class="btn btn-success">Save</button>
</div>
@section('js')
    <script>

        /**
         * Events
         */
        $(document).on('click', '#btn-add-new-product', function () {
            const rowId = Date.now();
            const productRow = `
            <tr id="product-${rowId}">
                <td>
                    <select name="products[${rowId}][product_id]"
                    row-id="product-${rowId}"
                    class="form-control  input-product-product_id">
                        @foreach($products as $product)
                            <option value="{{ $product->id }}" data-price="{{ $product->price }}">
                                {{ $product->name }} | {{ $product->price }}
                            </option>
                        @endforeach
                    </select>
                </td>
                <td>
                    <input type="number"
                    name="products[${rowId}][quantity]"
                    value="1"
                    row-id="product-${rowId}"
                    class="form-control input-product-quantity">
                </td>
                <td>
                    <input type="number"
                    name="products[${rowId}][price]"
                    row-id="product-${rowId}"
                    value="{{ $products->first()->price }}"
                    readonly
                    class="form-control input-product-price">
                </td>
                <td>
                    <input type="number"
                    name="products[${rowId}][total]"
                    row-id="product-${rowId}"
                    readonly
                    value="{{ $products->first()->price }}"
                    class="form-control input-product-total">
                </td>
                <td>
                    <button type="button" class="btn btn-danger row-delete" row-id="product-${rowId}">-</button>
                </td>
            </tr>
            `;
            $('#products-list').append(productRow);
        });

        $(document).on('click', '.row-delete', function () {
            const rowId = '#' + $(this).attr('row-id');
            $(rowId).remove();
        });

        $(document).on('keyup', '.input-product-quantity', function () {
            const rowId = '#' + $(this).attr('row-id');
            calculateTotal(rowId);
        });

        $(document).on('change', '.input-product-product_id', function () {
            const rowId = '#' + $(this).attr('row-id'),
                price = $(this).children("option:selected").data('price')
            ;
            $(`${rowId} .input-product-price`).val(price);
            calculateTotal(rowId);
        });

        ///////////////////////////
        /**
         * Functions
         */

        /**
         * @param rowId
         */
        function calculateTotal(rowId) {
            const quantity = $(`${rowId} .input-product-quantity`).val(),
                price = $(`${rowId} .input-product-price`).val(),
                total = price * quantity;

            $(`${rowId} .input-product-total`).val(total);
        }
    </script>
@endsection

session/resources/views/admin/order/index.blade.php
@extends('layouts.app')

@section('title', 'All Orders')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Orders</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item active">All Orders</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <div class="row">
                            <div class="col">
                                <form>
                                    <select name="limit" id="">
                                        <option value="5" {{ Request::get('limit') == 5? 'selected' : '' }}>5</option>
                                        <option value="10" {{ Request::get('limit') == 10? 'selected' : '' }}>10</option>
                                        <option value="25" {{ Request::get('limit') == 25? 'selected' : '' }}>25</option>
                                    </select>
                                    <button type="submit">update</button>
                                </form>
                            </div>
                            <div class="col text-center">
                                <form class="d-flex justfy-between">
                                    <input type="text" name="search" class="form-control">
                                    <button type="submit" class="btn btn-info">Searching</button>
                                    <a href="{{ route('admin.orders.index') }}"class="btn btn-warning">Reset</a>
                                </form>
                            </div>
                            <div class="col text-right">
                                <a href="{{ route('admin.orders.create') }}" class="btn btn-success">Create</a>
                            </div>
                        </div>



                        <table  class="table table-bordered table-data mt-4">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Client Name</th>
                                <th>User Name</th>
                                <th>Payment Method</th>
                                <th>Total Amount</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                           
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-end">
                            {!! $orders->links() !!}
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

@section('js')
    <script>

        $(function () {
            getAllOrders();
        });

        $(document).on('click', '.delete', function (e) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // $(`#delete-${$(this).data('id')}`).submit();
                    $.ajax({
                        url: $(this).data('url'),
                        type: 'POST',
                        data: {
                            _method : 'DELETE',
                            _token : '{{ csrf_token() }}'
                        },
                        success: function (res) {
                            if (result.value) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                );

                                getAllOrders();
                            }
                        }
                    });
                }
            })
        });

        $(document).on('click', '.page-link', function (e) {
            e.preventDefault();
            getAllOrders($(this).text())
        });

        function getAllOrders(page = 1) {
            $.ajax({
                url: '{{ route('admin.orders.get-orders') }}?page=' + page,
                type: 'GET',
                success: function (res) {
                    $('.table-data tbody').html(res);
                }
            })
        }
    </script>
@endsection

session/resources/views/admin/order/show.blade.php
@extends('layouts.app')

@section('title', 'All Orders')

@section('content')
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Orders</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">admin</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.orders.index') }}">Orders</a></li>
                        <li class="breadcrumb-item active">Show Order: {{ $order->id }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    
    <div class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="card card-body">
                    
                    <h2>Order : {{ $order->id }}</h2>
                    <p>Client Name: {{ $order->client->name }}</p>
                    <hr>
                    <table class="table table-bordered">
                        <thead>
                            <tr class="text-center">
                                <th>Product name</th>
                                <th>Price</th>
                                <th>Order quantity</th>
                                <th>Total</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($order->products as $productdetails)
                            <tr class="text-center">
                                <td>{{ $productdetails->name }}</td>
                                <td>{{ ($productdetails->pivot->price)  }} $</td>
                                <td>{{ ($productdetails->pivot->quantity) }}</td>
                                <td>{{( $productdetails->pivot->total) }}</td>
                                <td>{{$productdetails->pivot->created_at}}</td>
                                
                                
                            </tr>
                            @endforeach
                        </tbody>
                    </table>                       
                                     <div class="d-flex justify-content-around">   
                    <h3 class="text-center mt-3 mb-3"> Total amount : {{($order->total_amount)}}$</h3>
                    <h3 class="text-center mt-3 mb-3"> payment method : {{($order->payment->name)}}</h3>
</div>
                    <a href="{{ route('admin.orders.edit', $order) }}" class="btn btn-primary">Edit</a>
                </div>
            </div>
         
        </div>
    </div>
    
</div>
@endsection

session/resources/views/admin/order/table.blade.php
@foreach($orders as $order)
    <tr>
        <td>{{ $order->id }}</td>
        <td>{{$order->client?$order->client->name:""}}</td>
        <td>{{ $order->user->name }}</td>
        <td>                               
            {{$order->payment?$order->payment->name:""}}                                  
        </td>
        <td>{{ $order->total_amount }} $</td>                                        
        <td>
            <a href="{{ route('admin.orders.show', $order) }}" class="btn btn-info">Show</a>
            <a href="{{ route('admin.orders.edit', $order) }}" class="btn btn-primary">Edit</a>                                          
            <button type="button" class="btn btn-danger delete" data-url="{{ route('admin.orders.destroy', $order)}}">Delete</button>                                       
            </td>
    </tr>
@endforeach