session/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
define('pagenation_count' ,5);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth' ]
], function () {
    
    Route::group([
        'middleware' => ['admin']
    ], function () {

    Route::group([
        'prefix' => 'clients',
        'as' => 'clients.'
    ], function () {
        Route::get('/get-clients', 'ClientController@getClients')->name('get-clients');
    });
    Route::resource('/clients', 'ClientController');



    Route::group([
        'prefix' => 'categories',
        'as' => 'categories.'
    ], function () {
        Route::get('/get-categories', 'CategoryController@getCategories')->name('get-categories');
    });
    Route::resource('/categories', 'CategoryController');



    Route::group([
        'prefix' => 'products',
        'as' => 'products.'
    ], function () {
        Route::get('/get-products', 'ProductController@getProducts')->name('get-products');
    });
    Route::resource('/products', 'ProductController');



    Route::group([
        'prefix' => 'orders',
        'as' => 'orders.'
    ], function () {
        Route::get('/get-orders', 'OrderController@getOrders')->name('get-orders');
    });
    
    Route::resource('/orders', 'OrderController');

    });


    Route::group([
        'prefix' => 'stocks',
        'as' => 'stocks.'
    ], function () {
        Route::get('/get-stocks', 'StockController@getStocks')->name('get-stocks');
    });
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::get('/search', 'SearchController@index')->name('search-for-product');
    Route::get('/search-product', 'SearchController@search');
    
    Route::resource('/stocks', 'StockController');

    Route::get('/create-inventory/{product}' , 'StockController@create')->name('inventory');
});


Route::group([
    'prefix' => 'orders',
    'as' => 'orders.'
], function () {
    Route::get('/get-orders', 'Front\BuyControlle@getOrders')->name('get-product-orders');
});

Route::get('/buy/{product}', 'Front\BuyController@create')->name('buyproduct');
Route::resource('/order', 'Front\BuyController');

Route::get('/', function () {
    return view('searchbox');
});


Auth::routes();
Route::get('/clients/register' , 'Auth\RegisterController@clientRegisterForm')->name('client-register-form');
Route::post('/clients/register' , 'Auth\RegisterController@registerclient')->name('register-client');
Route::get('/clients/login' , 'Auth\LoginController@clientLoginForm')->name('client-login-form');
Route::post('/clients/login' , 'Auth\LoginController@loginclient')->name('login-client');
Route::get('/clients/logout' , 'Auth\LoginController@clientlogout')->name('logout-client');

session/app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User ;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Hash;

class Client extends User
{
    protected $fillable = [
        'id','name', 'email','password'
    ];
    public function order()
    {
        return $this->hasmany(Order::class);
    }
    public function setPasswordAttribute($plainpassword)
    {
        $this->attributes['password']=Hash::make($plainpassword);
    }
}

session/app/Http/Controllers/Api/ClientController.php
<?php

namespace App\Http\Controllers\Api;

use AElnemr\RestFullResponse\CoreJsonResponse;
use App\Client;
use App\Http\Controllers\Controller;
use App\Http\Resources\ClientList;
use App\Http\Resources\ClientShow;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    use CoreJsonResponse;

    public function index()
    {
        $clients = ClientList::collection(Client::all());
        return $this->ok($clients->resolve());
    }

    public function show(Client $client)
    {
        return new ClientShow($client);
    }
}

session/app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;
use App\Client;
use Illuminate\Http\Request;

class clientController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        
        $q = $request->query('search');

        return view('admin.client.index', [
            'clients' => Client::where('name', 'LIKE', "%{$q}%")
                ->paginate($request->query('limit', pagenation_count))
        ]);
    }
    public function getClients(Request $request)
    {
        return view('admin.client.new', [
            'clients' => Client::query()->paginate(pagenation_count)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.client.create', [
            'clients' => Client::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $client = Client::create($request->all());

        return redirect(route('admin.clients.show', $client));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        return view('admin.client.show', [
            'client'=> $client
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('admin.client.edit', [
            'client' => $client,
            'clients' => Client::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        
        $client->update($request->all());
        return redirect(route('admin.clients.show', $client));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();
        return  redirect(route('admin.clients.index'));
    }

    
}

session/resources/views/admin/client/create.blade.php
@extends('layouts.app')

@section('title', 'All Categories')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Categories</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.categories.index') }}">categories</a></li>
                            <li class="breadcrumb-item active">Create new category</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.clients.store') }}" method="post">
                           @include('admin.client.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

session/resources/views/admin/client/edit.blade.php
@extends('layouts.app')

@section('title', 'All Clients')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Clients</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.categories.index') }}">client</a></li>
                            <li class="breadcrumb-item active">Create new client</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.clients.update', $client) }}"
                              method="post">
                            @method('PUT')
                           @include('admin.client.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

session/resources/views/admin/client/form.blade.php
@csrf

<div class="form-group">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" class="form-control" value="{{ isset($client)?$client->name : '' }}">
    

</div>
<div class="form-group">
    <label for="email">Email</label>
    <input type="text" name="email" id="email"  class="form-control" value="{{ isset($client)?$client->email : '' }}">
        
   
    
</div>
<div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" id="password"  class="form-control" value="{{ isset($client)?$client->password: '' }}">
        
   
    
</div>
<div class="text-center">
    <button type="submit" class="btn btn-success">Save</button>
</div>

session/resources/views/admin/client/index.blade.php
@extends('layouts.app')

@section('title', 'All Clients')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Clients</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item active">All Clients</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <div class="row">
                            <div class="col">
                                <form>
                                    <select name="limit" id="">
                                        <option value="5" {{ Request::get('limit') == 5? 'selected' : '' }}>5</option>
                                        <option value="10" {{ Request::get('limit') == 10? 'selected' : '' }}>10</option>
                                        <option value="25" {{ Request::get('limit') == 25? 'selected' : '' }}>25</option>
                                    </select>
                                    <button type="submit">update</button>
                                </form>
                            </div>
                            <div class="col text-center">
                                <form class="d-flex justfy-between" >
                                    <input type="text" name="search" class="form-control">
                                    <button type="submit" class="btn btn-info">Searching</button>
                                    <a href="{{ route('admin.clients.index') }}" class="btn btn-warning">Reset</a>
                                </form>
                            </div>
                            <div class="col text-right">
                                <a href="{{ route('admin.clients.create') }}" class="btn btn-success">Create</a>
                            </div>
                        </div>



                        <table class="table table-bordered table-data mt-4">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>name</th>
                                    <th>Email</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-end">
                            {!! $clients->links() !!}
                        </div>
                    </div>
                </div>
        <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    <!-- /.content -->
    </div>
@endsection


@section('js')
    <script>

        $(function () {
            getAllClients();
        });

        $(document).on('click', '.delete', function (e) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // $(`#delete-${$(this).data('id')}`).submit();
                    $.ajax({
                        url: $(this).data('url'),
                        type: 'POST',
                        data: {
                            _method : 'DELETE',
                            _token : '{{ csrf_token() }}'
                        },
                        success: function (res) {
                            if (result.value) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                );

                                getAllClients();
                            }
                        }
                    });

                   
                }
            })
        });

        $(document).on('click', '.page-link', function (e) {
            e.preventDefault();
            getAllClients($(this).text())
        });

        function getAllClients(page = 1) {
            $.ajax({
                url: '{{ route('admin.clients.get-clients') }}?page=' + page,
                type: 'GET',
                success: function (res) {
                    $('.table-data tbody').html(res);
                }
            })
        }
    </script>
@endsection

session/resources/views/admin/client/new.blade.php
@foreach($clients as $client)
    <tr>
        <td>{{ $client->id }}</td>
        <td>{{ $client->name }}</td>
        <td>{{ $client->email }}</td>
        <td>
            <a href="{{route('admin.clients.show', $client)}}" class="btn btn-info">Show</a>
            <a href="{{route('admin.clients.edit', $client)}}" class="btn btn-primary">Edit</a>
            <button type="button" class="btn btn-danger delete" data-url="{{ route('admin.clients.destroy', $client) }}">Delete</button>
        </td>
    </tr>
@endforeach

session/resources/views/admin/client/show.blade.php
@extends('layouts.app')

@section('title', 'All Clients')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Clients</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.categories.index') }}">clients</a></li>
                            <li class="breadcrumb-item active">Show Client: {{ $client->name }}</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <h2>client name: <br> {{ $client->name }}</h2>
                        <p>client email: <br> {{ $client->email}}</p>
                        
                        <a href="{{ route('admin.clients.edit', $client) }}" class="btn btn-primary">Edit</a>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection