session/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
define('pagenation_count' ,5);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth' ]
], function () {
    
    Route::group([
        'middleware' => ['admin']
    ], function () {

    Route::group([
        'prefix' => 'clients',
        'as' => 'clients.'
    ], function () {
        Route::get('/get-clients', 'ClientController@getClients')->name('get-clients');
    });
    Route::resource('/clients', 'ClientController');



    Route::group([
        'prefix' => 'categories',
        'as' => 'categories.'
    ], function () {
        Route::get('/get-categories', 'CategoryController@getCategories')->name('get-categories');
    });
    Route::resource('/categories', 'CategoryController');



    Route::group([
        'prefix' => 'products',
        'as' => 'products.'
    ], function () {
        Route::get('/get-products', 'ProductController@getProducts')->name('get-products');
    });
    Route::resource('/products', 'ProductController');



    Route::group([
        'prefix' => 'orders',
        'as' => 'orders.'
    ], function () {
        Route::get('/get-orders', 'OrderController@getOrders')->name('get-orders');
    });
    
    Route::resource('/orders', 'OrderController');

    });


    Route::group([
        'prefix' => 'stocks',
        'as' => 'stocks.'
    ], function () {
        Route::get('/get-stocks', 'StockController@getStocks')->name('get-stocks');
    });
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::get('/search', 'SearchController@index')->name('search-for-product');
    Route::get('/search-product', 'SearchController@search');
    
    Route::resource('/stocks', 'StockController');

    Route::get('/create-inventory/{product}' , 'StockController@create')->name('inventory');
});


Route::group([
    'prefix' => 'orders',
    'as' => 'orders.'
], function () {
    Route::get('/get-orders', 'Front\BuyControlle@getOrders')->name('get-product-orders');
});

Route::get('/buy/{product}', 'Front\BuyController@create')->name('buyproduct');
Route::resource('/order', 'Front\BuyController');

Route::get('/', function () {
    return view('searchbox');
});


Auth::routes();
Route::get('/clients/register' , 'Auth\RegisterController@clientRegisterForm')->name('client-register-form');
Route::post('/clients/register' , 'Auth\RegisterController@registerclient')->name('register-client');
Route::get('/clients/login' , 'Auth\LoginController@clientLoginForm')->name('client-login-form');
Route::post('/clients/login' , 'Auth\LoginController@loginclient')->name('login-client');
Route::get('/clients/logout' , 'Auth\LoginController@clientlogout')->name('logout-client');

session/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'description',
        'category_id',
        'price',
        'quantity',
        'img',
        'user_id'
    ];

    public function category(){
        return $this->belongsTo(Category::class);
    }
    public function user(){
        return $this->belongsTo(User::class,'user_id');
    }
    public function stock(){
        return $this->belongsTo(Stock::class);
    }
   
}

session/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use App\User;
use App\Http\Requests\ProductRequest;
use Illuminate\Http\Request;
use App\Traits\ProductTrait;

class ProductController extends Controller
{
    use ProductTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $q = $request->query('search');

        return view('admin.product.index', [
            'products' => Product::with(['category' , 'user' ]) 
                ->where('name', 'LIKE', "%{$q}%")
                ->paginate($request->query('limit', pagenation_count))
        ]);
    }
    public function getProducts(Request $request)
    {
        return view('admin.product.table', [
            'products' => Product::query()->paginate(pagenation_count)
        ]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.create', [
            'products' => Product::all(),
            'categories'=> Category::all(),
            'users'=> User::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $file_name = $this->saveImage($request->file('img'),'images/products');
        //$request->merge([
        //    'img'  => $file_name
        //]);
        $product = Product::create([
        'name' => $request->name,
        'img'=> $file_name,
        'description'=> $request->description,
        'category_id'=> $request->category_id,
        'price'=> $request->price,
        'quantity'=> $request->quantity,
        'user_id'=> $request->user_id
        
        
        
        
        ]);

        return redirect(route('admin.products.show', $product));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin.product.show', [
            'product'=> $product
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('admin.product.edit', [
            'product' => $product,
            'products' => Product::all(),
            'categories'=> Category::all(),
            'users'=> User::all()
            
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        
        $product->update($request->all());
        return redirect(route('admin.products.show', $product));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return  redirect(route('admin.products.index'));
    }

    
}

session/resources/views/admin/product/create.blade.php
@extends('layouts.app')

@section('title', 'All Products')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Products</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.products.index') }}">Products</a></li>
                            <li class="breadcrumb-item active">Create new Products</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.products.store') }}" method="post" enctype="multipart/form-data">
                           @include('admin.product.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

session/resources/views/admin/product/edit.blade.php
@extends('layouts.app')

@section('title', 'All Products')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Products</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.products.index') }}">Products</a></li>
                            <li class="breadcrumb-item active">edit Product</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <form action="{{ route('admin.products.update', $product) }}"
                              method="post">
                            @method('PUT')
                           @include('admin.product.form')
                        </form>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

session/resources/views/admin/product/form.blade.php
@csrf
<div class="form-group">
    <label for="category_id"> Category name</label>
    <select name="category_id" id="category_id" class="form-control">
        <option value>Not set</option>
        @foreach($categories as $category) 
            @if(isset($product))
                <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
            @else
                <option value="{{ $category->id }}" >{{ $category->name }}</option>  
            @endif
        @endforeach
    </select>
    @if ($errors->first('category_id'))
        <span class="text-danger">
          {{ $errors->first('category_id') }}
        </span>
    @endif
</div>
<div class="form-group">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" class="form-control" value="{{ isset($product)?$product->name : '' }}">
    @if ($errors->first('name'))
        <span class="text-danger">
          {{ $errors->first('name') }}
        </span>
    @endif

</div>
<div class="form-group">
    <label for="description">Description</label>
    <textarea name="description" id="description" cols="30" rows="10" class="form-control">
        {{ isset($product)?$product->description : '' }}
    </textarea>
    @if ($errors->first('description'))
        <span class="text-danger">
          {{ $errors->first('description') }}
        </span>
    @endif
</div>
<div class="form-group">
    <label for="price">Price</label>
    <input type="text" name="price" id="price" class="form-control" value="{{ isset($product)?$product->price : '' }}">
    @if ($errors->first('price'))
        <span class="text-danger">
          {{ $errors->first('price') }}
        </span>
    @endif

</div>
<div class="form-group">
    <label for="quantity">Quintity</label>
    <input type="text" name="quantity" id="quantity" class="form-control" value="{{ isset($product)?$product->quantity : '' }}">
    @if ($errors->first('quantity'))
        <span class="text-danger">
          {{ $errors->first('quantity') }}
        </span>
    @endif

</div>
<div class="form-group">
    <label for="img">img</label>
    <input type="file" name="img" id="quntity" class="form-control" 
    value="{{ isset($product)?$product->img : '' }}">
    @if ($errors->first('img'))
        <span class="text-danger">
          {{ $errors->first('img') }}
        </span>
    @endif

</div>

<div class="form-group">
    <label for="user_id"> user</label>
    <select name="user_id" id="user_id" class="form-control">
        <option value>Not set</option>
        @foreach($users as $user) 
            @if(isset($product))
                <option value="{{ $user->id }}" selected>{{ $user->name }}</option>
            @else
                <option value="{{ $user->id }}" >{{ $user->name }}</option>  
            @endif
        @endforeach
    </select>
    @if ($errors->first('user_id'))
        <span class="text-danger">
          {{ $errors->first('user_id') }}
        </span>
    @endif
</div>

<div class="text-center">
    <button type="submit" class="btn btn-success">Save</button>
</div>

session/resources/views/admin/product/index.blade.php
@extends('layouts.app')

@section('title', 'All Products')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Products</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item active">All Products</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <div class="row">
                            <div class="col">
                                <form>
                                    <select name="limit" id="">
                                        <option value="5" {{ Request::get('limit') == 5? 'selected' : '' }}>5</option>
                                        <option value="10" {{ Request::get('limit') == 10? 'selected' : '' }}>10</option>
                                        <option value="25" {{ Request::get('limit') == 25? 'selected' : '' }}>25</option>
                                    </select>
                                    <button type="submit">update</button>
                                </form>
                            </div>
                            <div class="col text-center">
                                <form class="d-flex justfy-between" >
                                    <input type="text" name="search" class="form-control">
                                    <button type="submit" class="btn btn-info">Searching</button>
                                    <a href="{{ route('admin.products.index') }}" class="btn btn-warning">Reset</a>
                                </form>
                            </div>
                            <div class="col text-right">
                                <a href="{{ route('admin.products.create') }}" class="btn btn-success">Create</a>
                            </div>
                        </div>



                        <table class="table table-bordered table-data mt-4">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Photo</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>category</th>
                                <th>user</th>
                                <th>description</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                           
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-end">
                            {!! $products->links() !!}
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection


@section('js')
    <script>

        $(function () {
            getAllProducts();
        });

        $(document).on('click', '.delete', function (e) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // $(`#delete-${$(this).data('id')}`).submit();
                    $.ajax({
                        url: $(this).data('url'),
                        type: 'POST',
                        data: {
                            _method : 'DELETE',
                            _token : '{{ csrf_token() }}'
                        },
                        success: function (res) {
                            if (result.value) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                );

                                getAllProducts();
                            }
                        }
                    });

                }
            })
        });

        $(document).on('click', '.page-link', function (e) {
            e.preventDefault();
            getAllProducts($(this).text())
        });

        function getAllProducts(page = 1) {
            $.ajax({
                url: '{{ route('admin.products.get-products') }}?page=' + page,
                type: 'GET',
                success: function (res) {
                    $('.table-data tbody').html(res);
                }
            })
        }
    </script>
@endsection

session/resources/views/admin/product/show.blade.php
@extends('layouts.app')

@section('title', 'All Products')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Products</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.products.index') }}">Products</a></li>
                            <li class="breadcrumb-item active">Show Category: {{ $product->name }}</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <h2>Title: <br> {{ $product->name }}</h2>
                        <p>Description: <br> {{ $product->description }}</p>
                        @if ($product->category)
                            Parent: <a href="{{ route('admin.categories.show', $product->category) }}">{{ $product->category->name }}</a>
                        @endif
                        <p>price: <br> {{ $product->price }}</p>
                        <p>quantity: <br> {{ $product->quantity }}</p>
                        <p>img: <br> {{ $product->img}}</p>
                        <p>user: <br> {{ $product->user->name }}</p>
                        <a href="{{ route('admin.products.edit', $product) }}" class="btn btn-primary">Edit</a>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

session/resources/views/admin/product/table.blade.php
@foreach($products as $product)
    <tr>
        <td>{{ $product->id }}</td>
        <td><img  style="width: 90px; height: 90px;" src="{{asset('images/products/'.$product->img)}}"></td>
        <td>{{ $product->name }}</td>
        <td>{{ $product->price }}</td>
        <td>{{ $product->quantity }}</td>
        <td>
            @if ($product->category)
                <a href="{{ route('admin.categories.show', $product->category) }}" class="link-item">{{ $product->category->name }}</a>
            @endif
        </td>
        <td>
            @if ($product->user)
                {{ $product->user->name }}
            @endif
        </td>
        <td>{{ $product->description }}</td>
        <td>
            <a href="{{ route('admin.products.show', $product) }}" class="btn btn-info">Show</a>
            <a href="{{ route('admin.products.edit', $product) }}" class="btn btn-primary">Edit</a>                                       
            <button type="button" class="btn btn-danger delete" data-url="{{  route('admin.products.destroy', $product) }}">Delete</button>
        </td>
    </tr>
@endforeach